### ISSUE TITLE
encountered an unexpected error

### ISSUE THREAD

**Issue by webzor** [chegele/ValheimManager#23]
[30.8.2024, 21:20:03] GENERAL ValheimManager -  Checking for updates...
[30.8.2024, 21:20:03] GENERAL ValheimManager -  Valheim Manager is up to date.
[30.8.2024, 21:20:03] GENERAL ValheimManager -  Attempting to open ports 2456,2457,2458...
[30.8.2024, 21:20:13] GENERAL ValheimManager -  Successfully opened the ports.
[30.8.2024, 21:20:13] GENERAL ValheimManager -  Generating the launch file...
[30.8.2024, 21:20:13] GENERAL ValheimManager -  Starting the valheim dedicated server...
[30.8.2024, 21:20:13] ERROR   ValheimManager -  The Valheim Manager has encountered an unexpected error.
Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at ValheimLauncher.startValheim (C:\Users\e_ave\AppData\Roaming\npm\node_modules\valheim-manager\src\launcher.js:130:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async execute (C:\Users\e_ave\AppData\Roaming\npm\node_modules\valheim-manager\src\console.js:107:32)
    
   I am trying to activate the server, but getting this error. Any tips?

**Comment by chegele** [comment]
This appears to be the result of a vulnerability that was patched. I can see about getting it fixed.

https://github.com/nodejs/node/issues/52554#issuecomment-2061405161

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: webzor ***@***.***>
Sent: Friday, August 30, 2024 3:22:17 PM
To: chegele/ValheimManager ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [chegele/ValheimManager] encountered an unexpected error (Issue #23)


[30.8.2024, 21:20:03] GENERAL ValheimManager - Checking for updates...
[30.8.2024, 21:20:03] GENERAL ValheimManager - Valheim Manager is up to date.
[30.8.2024, 21:20:03] GENERAL ValheimManager - Attempting to open ports 2456,2457,2458...
[30.8.2024, 21:20:13] GENERAL ValheimManager - Successfully opened the ports.
[30.8.2024, 21:20:13] GENERAL ValheimManager - Generating the launch file...
[30.8.2024, 21:20:13] GENERAL ValheimManager - Starting the valheim dedicated server...
[30.8.2024, 21:20:13] ERROR ValheimManager - The Valheim Manager has encountered an unexpected error.
Error: spawn EINVAL
at ChildProcess.spawn (node:internal/child_process:421:11)
at spawn (node:child_process:761:9)
at ValheimLauncher.startValheim (C:\Users\e_ave\AppData\Roaming\npm\node_modules\valheim-manager\src\launcher.js:130:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async execute (C:\Users\e_ave\AppData\Roaming\npm\node_modules\valheim-manager\src\console.js:107:32)

I am trying to activate the server, but getting this error. Any tips?
